### ISSUE TITLE
容器无法启动，nginx配置文件不存在

### ISSUE THREAD

**Issue by helloxz** [Safe3/openresty-manager#7]
使用`docker-compose.yaml`，内容如下：

```
services:
  openresty-manager:
   image: uusec/openresty-manager:latest
   ulimits:
     nproc: 65535
     nofile:
       soft: 102400
       hard: 102400
   container_name: openresty-manager
   restart: always
   network_mode: host
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/resolv.conf:/etc/resolv.conf:ro
     - ./acme:/opt/om/acme
     - ./data:/opt/om/data
     - ./conf:/opt/om/nginx/conf
```

启动后无法访问，查看日志：`failed to start OpenResty: nginx: [emerg] open() "/opt/om/nginx/conf/nginx.conf" failed (2: No such file or directory)`

容器内的启动脚本没有自动拷贝配置文件吗？还是啥原因？
